import io
import os
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
import torch
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="TrOCR Inference API")

# Setup CORS for frontend to allow local requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Go up one directory from 'backend' to reach the workspace root where the model folder is
WORKSPACE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(WORKSPACE_DIR, "trocr-iam-model")

print(f"Loading model from: {MODEL_DIR}")

# Load model and processor globally
try:
    processor = TrOCRProcessor.from_pretrained(MODEL_DIR)
    model = VisionEncoderDecoderModel.from_pretrained(MODEL_DIR)
    
    # Check for Apple Silicon MPS or fallback to CPU
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
        
    model.to(device)
    model.eval()
    print(f"✅ Model successfully loaded on {device}")
except Exception as e:
    print(f"❌ Error loading model: {e}")
    processor = None
    model = None
    device = torch.device("cpu")

@app.post("/predict")
async def predict_text(file: UploadFile = File(...)):
    if not model or not processor:
        raise HTTPException(status_code=500, detail="Model is not loaded. Check backend console logs.")
        
    try:
        # Read image
        contents = await file.read()
        image = Image.open(io.BytesIO(contents)).convert("RGB")
        
        # Preprocess
        pixel_values = processor(images=image, return_tensors="pt").pixel_values.to(device)
        
        # Inference
        with torch.no_grad():
            generated_ids = model.generate(pixel_values, max_new_tokens=100)
            
        # Postprocess
        generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
        
        # Groq Post-Correction
        try:
            client = Groq(api_key=os.getenv("GROQ_API_KEY"))
            completion = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {
                        "role": "system",
                        "content": "You are a text correction expert. The following text was generated by an OCR model and might contain spelling, grammar, or formatting errors. Correct the text, preserving its precise original meaning and structure as much as possible. Reply ONLY with the corrected text, absolutely no other conversation, output, or introductory comments."
                    },
                    {
                        "role": "user",
                        "content": generated_text
                    }
                ],
                temperature=0.1,
            )
            corrected_text = completion.choices[0].message.content.strip()
            
            return {
                "text": corrected_text,
                "original_ocr_text": generated_text
            }
        except Exception as groq_err:
            print(f"Groq API Error: {groq_err}")
            return {"text": generated_text, "original_ocr_text": generated_text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")
